### ISSUE TITLE
ES6 syntax

### ISSUE THREAD

**Issue by janfabian** [graphql-compose/graphql-compose-pagination#4]
Hi, latest build of `graphql-compose-pagination` gives me following error.

```
/Users/janfabian/dev/ingrid-backend/node_modules/graphql-compose-pagination/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { import { composeWithPagination } from './composeWithPagination';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at preparePaginationResolver (/Users/janfabian/dev/ingrid-backend/node_modules/graphql-compose-mongoose/lib/composeWithMongoose.js:138:33)
    at createResolvers (/Users/janfabian/dev/ingrid-backend/node_modules/graphql-compose-mongoose/lib/composeWithMongoose.js:128:5)
    at composeWithMongoose (/Users/janfabian/dev/ingrid-backend/node_modules/graphql-compose-mongoose/lib/composeWithMongoose.js:56:5)
    at Object.<anonymous> (/Users/janfabian/dev/ingrid-backend/src/api/tc/idea.js:4:16)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at glob.sync.forEach.filename (/Users/janfabian/dev/ingrid-backend/src/api/gql/schema.js:5:39)
    at Array.forEach (<anonymous>)
```

I'm not using `graphql-compose-pagination` directly, but it's dependency of `graphql-compose-mongoose`

**Comment by nodkz** [comment]
Thank a lot for reporting. 

Already fixed. Sorry for inconvenience 😉

**Comment by janfabian** [comment]
Thank you for the amazing work
